steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - deploy/Dockerfile # <— path from repo root to the file
      - -t
      - gcr.io/$PROJECT_ID/hope
      - . # build context = repo root

images:
  - gcr.io/$PROJECT_ID/hope
