steps:
  # Build & push the image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/hope", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/hope"]

  # Deploy to Cloud Run (replace REGION as needed)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "hope",
        "--image",
        "gcr.io/$PROJECT_ID/hope",
        "--platform",
        "managed",
        "--region",
        "$REGION",
        "--allow-unauthenticated",
      ]

images:
  - "gcr.io/$PROJECT_ID/hope"

options:
  logging: CLOUD_LOGGING_ONLY
